[versions]
compileSdk = "33"
minSdk = "21"
targetSdk = "32"
versionCode = "1"
versionName = "1.0.0"
testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
consumerProguardFiles = "consumer-rules.pro"

coreKtx = "1.7.0"
appcompat = "1.3.0"
material = "1.4.0"
constraintlayout = "2.1.3"
uiKtx = "2.3.5"
junit = "4.13.2"
testJunit = "1.1.3"
espresso = "3.4.0"
retrofit = "2.4.0"
okHttp = "3.10.0"
okHttpLogging = "3.9.0"
glide = "4.5.0"
glideTransformations = "2.0.1"
gson = "2.8.2"
rxAndroid = "2.0.2"
rxJava = "2.1.12"
rxBus = "1.5"
gifView = "1.2.25"
logger = "2.2.0"
toasty = "1.5.2"
banner = "2.2.2"
smart_refresh = "2.0.5"
autoSize = "v1.2.1"
adapterHelper = "4.0.0-beta04"
flexBoxLayout = "3.0.0"
dataStore = "1.0.0"
agentWeb = "v5.0.6-androidx"

[libraries]
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
navigationFragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "uiKtx" }
navigationUiKtx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "uiKtx" }
junit = { module = "junit:junit", version.ref = "junit" }
testJunit = { module = "androidx.test.ext:junit", version.ref = "testJunit" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

retrofit = {module = "com.squareup.retrofit2:retrofit",version.ref = "retrofit"}
retrofitGson = {module = "com.squareup.retrofit2:converter-gson",version.ref = "retrofit"}
retrofitRxJava = {module = "com.squareup.retrofit2:adapter-rxjava2",version.ref = "retrofit"}
okHttp = {module = "com.squareup.okhttp3:okhttp",version.ref = "okHttp"}
okHttpLogging = {module = "com.squareup.okhttp3:logging-interceptor",version.ref = "okHttpLogging"}
glide = {module = "com.github.bumptech.glide:glide",version.ref = "glide"}
glideTransformations = {module = "jp.wasabeef:glide-transformations",version.ref = "glideTransformations"}
gson = {module = "com.google.code.gson:gson",version.ref = "gson"}

rxAndroid = {module = "io.reactivex.rxjava2:rxandroid",version.ref = "rxAndroid"}
rxJava = {module = "io.reactivex.rxjava2:rxjava",version.ref = "rxJava"}
rxBus = {module = "com.blankj:rxbus",version.ref = "rxBus"}

gifView = {module = "pl.droidsonroids.gif:android-gif-drawable",version.ref = "gifView"}
logger = {module = "com.orhanobut:logger",version.ref = "logger"}
toasty = {module = "com.github.GrenderG:Toasty",version.ref = "toasty"}
banner = {module = "io.github.youth5201314:banner",version.ref = "banner"}

smart_refresh_kernel = {module = "io.github.scwang90:refresh-layout-kernel",version.ref = "smart_refresh"}
smart_refresh_head_classics = {module = "io.github.scwang90:refresh-header-classics",version.ref = "smart_refresh"}
smart_refresh_head_radar = {module = "io.github.scwang90:refresh-header-radar",version.ref = "smart_refresh"}
smart_refresh_head_falsify = {module = "io.github.scwang90:refresh-header-falsify",version.ref = "smart_refresh"}
smart_refresh_head_material = {module = "io.github.scwang90:refresh-header-material",version.ref = "smart_refresh"}
smart_refresh_food_ball = {module = "io.github.scwang90:refresh-footer-ball",version.ref = "smart_refresh"}
smart_refresh_food_classics = {module = "io.github.scwang90:refresh-footer-classics",version.ref = "smart_refresh"}

autoSize = {module = "com.github.JessYanCoding:AndroidAutoSize",version.ref = "autoSize"}
adapterHelper = {module = "io.github.cymchad:BaseRecyclerViewAdapterHelper",version.ref = "adapterHelper"}
flexBoxLayout = {module = "com.google.android.flexbox:flexbox",version.ref = "flexBoxLayout"}
dataStore = {module = "androidx.datastore:datastore-preferences",version.ref = "dataStore"}
dataStoreCore = {module = "androidx.datastore:datastore-preferences-core",version.ref = "dataStore"}
agentWeb = {module = "com.github.Justson.AgentWeb:agentweb-core",version.ref = "agentWeb"}


[bundles]
andorid_base = ["coreKtx","appcompat","material","constraintlayout"]
junit = ["junit","testJunit"]
net = ["retrofit","retrofitGson","retrofitRxJava","okHttp","okHttpLogging","gson"]
smart_refresh = ["smart_refresh_kernel","smart_refresh_head_classics","smart_refresh_head_radar",
    "smart_refresh_head_falsify","smart_refresh_head_material","smart_refresh_food_ball","smart_refresh_food_classics"]

[plugins]
application = { id = "com.android.application"}
kotlin = {id = "org.jetbrains.kotlin.android"}
library = {id = "com.android.library"}


